// https://www.codewars.com/kata/5a331ea7ee1aae8f24000175/train/javascript

// Problem Description
// A coloured triangle is created from a row of colours, each of which is red, green or blue. Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If they are different, the missing colour is used in the new row. This is continued until the final row, with only a single colour, is generated.

// For example, different possibilities are:

// Colour here:            G G        B G        R G        B R
// Becomes colour here:     G          R          B          G
// With a bigger example:

// R R G B R G B B
//  R B R G B R B
//   G G B R G G
//    G R G B G
//     B B R R
//      B G R
//       R B
//        G
// You will be given the first row of the triangle as a string and its your job to return the final colour which would appear in the bottom row as a string. In the case of the example above, you would be given 'RRGBRGBB', and you should return 'G'.

// Constraints
// 1 <= length(row) <= 10 ** 5

// The input string will only contain the uppercase letters 'B', 'G' or 'R'.

// The exact number of test cases will be as follows:

// 100 tests of 100 <= length(row) <= 1000
// 100 tests of 1000 <= length(row) <= 10000
// 100 tests of 10000 <= length(row) <= 100000
// Examples
// triangle('B') == 'B'
// triangle('GB') == 'R'
// triangle('RRR') == 'R'
// triangle('RGBG') == 'B'
// triangle('RBRGBRB') == 'G'
// triangle('RBRGBRBGGRRRBGBBBGG') == 'G'


function helper(str, row, col) {
  if (row < 4) return hash(str.slice(col, col + row));

  let step = 4;
  while (step * 3 - 2 <= row) step = step * 3 - 2;

  const left = helper(str, row - step + 1, col);
  const right = helper(str, row - step + 1, col + step - 1);
  return getNext(left + right);
}

function hash(str) {
  let current = str.split('');
  let next;
  while (current.length > 1) {
    next = current.map((c, i) => {
      if (i == current.length - 1) return '';
      if (c == current[i + 1]) return c;
      
      return getNext(c + current[i + 1]);
    }); 
    next.pop();
    current = next;
  }
  return current[0];
}
function getNext(t) {
  if (t === 'RG' || t == 'GR' || t == 'BB') return 'B';
  if (t == 'RB' || t == 'BR' || t == 'GG') return 'G';
  if (t == 'BG' || t == 'GB' || t == 'RR') return 'R';
}

function triangle(str) {
  return helper(str, str.length, 0);
}

console.log(triangle('RGBG'))